services:
  wordpress:
    build:
      context: .
      dockerfile: Dockerfile    
    volumes:
      - 'wordpress-files:/var/www/html'
    environment:
      WORDPRESS_DB_HOST: $WORDPRESS_DB_HOST
      WORDPRESS_DB_USER: $WORDPRESS_DB_USER
      WORDPRESS_DB_PASSWORD: $WORDPRESS_DB_PASSWORD
      WORDPRESS_DB_NAME: $WORDPRESS_DB_NAME
      WORDPRESS_TABLE_PREFIX: $WORDPRESS_TABLE_PREFIX
    
    depends_on:
      - mariadb-wordpress
    healthcheck:
      test:
        - CMD
        - curl
        - '-f'
        - 'http://127.0.0.1'
      interval: 2s
      timeout: 10s
      retries: 10
    container_name: wordpress
    restart: unless-stopped
       

  mariadb-wordpress:
    image: 'mariadb:11'
    volumes:
      - 'mariadb-data:/var/lib/mysql'
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: $WORDPRESS_DB_ROOT_PASSWORD
      MYSQL_DATABASE: $WORDPRESS_DB_NAME
      MYSQL_USER: $WORDPRESS_DB_USER
      MYSQL_PASSWORD: $WORDPRESS_DB_PASSWORD
         
    healthcheck:
      test:
        - CMD
        - healthcheck.sh
        - '--connect'
        - '--innodb_initialized'
      interval: 5s
      timeout: 20s
      retries: 10
    container_name: mariadb-wordpress
    restart: unless-stopped    
   
volumes:
  wordpress-files:
  mariadb-data: